/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chenenyu_security_Security */

#ifndef _Included_com_chenenyu_security_Security
#define _Included_com_chenenyu_security_Security
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chenenyu_security_Security
 * Method:    getSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chenenyu_security_Security_getSecret
  (JNIEnv *, jclass);

/*
 * Class:     com_chenenyu_security_Security
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chenenyu_security_Security_getStr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
